<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-K4TMDRTS" failures="2" tests="4" name="Command line test" time="1.057" errors="0" timestamp="2022-03-10T08:34:13 IST">
  <testcase classname="hyrlisteners.TestClass1" name="testMethod3" time="1.026">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method hyrlisteners.TestClass1.testMethod3() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method hyrlisteners.TestClass1.testMethod3() didn't finish within the time-out 1000
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testMethod3 -->
  <testcase classname="hyrlisteners.TestClass1" name="testMethod1" time="0.0"/>
  <testcase classname="hyrlisteners.TestClass1" name="testMethod2" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at hyrlisteners.TestClass1.testMethod2(TestClass1.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- testMethod2 -->
  <testcase classname="hyrlisteners.TestClass1" name="testMethod4" time="0.0">
    <skipped/>
  </testcase> <!-- testMethod4 -->
</testsuite> <!-- Command line test -->
